environment:
  nodejs_version: "6"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --non-interactive

before_test:
  - yarn lint

test_script:
  - yarn test

cache:
  - "%LOCALAPPDATA%\\Yarn"

build: off
