environment:
  nodejs_version: "6"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@6
  - npm install

test_script:
  - npm run lint
  - npm test

cache:
  - node_modules -> package.json

build: off
